HISTORICAL_QUOTES = [
    ("The best way to predict your future is to create it.", "Abraham Lincoln"),
    ("I came, I saw, I conquered.", "Julius Caesar"),
    ("To be or not to be, that is the question.", "William Shakespeare"),
    ("I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin, but by the content of their character.", "Martin Luther King Jr."),
    ("The only thing we have to fear is fear itself.", "Franklin D. Roosevelt"),
    ("In the middle of difficulty lies opportunity.", "Albert Einstein"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("Ask not what your country can do for you, ask what you can do for your country.", "John F. Kennedy"),
    ("That's one small step for a man, one giant leap for mankind.", "Neil Armstrong"),
    ("The unexamined life is not worth living.", "Socrates"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    ("Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", "Martin Luther King Jr."),
    ("I think, therefore I am.", "Rene Descartes"),
    ("Give me liberty, or give me death!", "Patrick Henry"),
    ("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    ("Injustice anywhere is a threat to justice everywhere.", "Martin Luther King Jr."),
    ("Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"),
    ("Those who cannot remember the past are condemned to repeat it.", "George Santayana"),
    ("Speak softly and carry a big stick.", "Theodore Roosevelt"),
    ("The ballot is stronger than the bullet.", "Abraham Lincoln"),
    ("If you want to go fast, go alone. If you want to go far, go together.", "African Proverb"),
    ("Veni, vidi, vici.", "Julius Caesar"),
    ("A house divided against itself cannot stand.", "Abraham Lincoln"),
    ("The only true wisdom is in knowing you know nothing.", "Socrates"),
    ("Genius is one percent inspiration and ninety-nine percent perspiration.", "Thomas Edison"),
    ("Courage is grace under pressure.", "Ernest Hemingway"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("Nothing is certain except death and taxes.", "Benjamin Franklin"),
    ("Eighty percent of success is showing up.", "Woody Allen"),
    ("To err is human, to forgive divine.", "Alexander Pope"),
    ("Knowledge is power.", "Sir Francis Bacon"),
    ("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
    ("Life is what happens when you're busy making other plans.", "John Lennon"),
    ("No one can make you feel inferior without your consent.", "Eleanor Roosevelt"),
    ("Not everything that is faced can be changed, but nothing can be changed until it is faced.", "James Baldwin"),
    ("He who has a why to live for can bear almost any how.", "Friedrich Nietzsche"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("Whenever you find yourself on the side of the majority, it is time to pause and reflect.", "Mark Twain"),
    ("Our lives begin to end the day we become silent about things that matter.", "Martin Luther King Jr."),
    ("Liberty, when it begins to take root, is a plant of rapid growth.", "George Washington"),
    ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
    ("Whatever you are, be a good one.", "Abraham Lincoln"),
    ("Imagination is more important than knowledge.", "Albert Einstein"),
    ("Well done is better than well said.", "Benjamin Franklin"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("I attribute my success to this: I never gave or took any excuse.", "Florence Nightingale"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt")
]
